-- Add updated_at column to tables that are missing it
ALTER TABLE IF EXISTS account_transaction ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS api_operation_metadata ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS cascade_recalc_job ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS cascade_recalc_log ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS event_outbox ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS member_tier_activity_log ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS member_unique_key ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS notification_outbox ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS point_type_definition ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS redemption_allocation ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS repayment_allocation ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS rule_snapshot ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS system_enum ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS transaction_event ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
